import Head from "next/head";
import { useRouter } from "next/router";
import { Hero } from "~/components/landing/Hero";
import { MeetTheMacedoniansIntro } from "~/components/landing/MeetTheMacedoniansIntro";
import {
  type IProfileSearchForm,
  ProfileSearchForm,
} from "~/components/profile/ProfileSearchForm";

export default function Home() {
  const router = useRouter();

  const handleSubmit = (data: IProfileSearchForm) => {
    const params = new URLSearchParams();

    Object.entries(data).forEach(([key, value]) => {
      if (value) params.set(key, String(value));
    });

    void router.push(`/search?${params.toString()}`);
  };

  return (
    <>
      <Head>
        <title>Meet The Macedonians</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Hero />
        <ProfileSearchForm onSubmit={handleSubmit} />
        <MeetTheMacedoniansIntro />
      </main>
    </>
  );
}
