import Head from "next/head";
import { useState } from "react";
import { Hero } from "~/components/landing/Hero";
import { ProfileList } from "~/components/profile/ProfileList";
import {
  ProfileSearchForm,
  type IProfileSearchForm,
} from "~/components/profile/ProfileSearchForm";
import { ProfileSetupForm } from "~/components/profile/ProfileSetupForm";
import { api } from "~/utils/api";

export default function Home() {
  const [profleSearchData, setProfleSearchData] =
    useState<IProfileSearchForm | null>(null);

  console.log(profleSearchData);

  const { data: profiles } = api.profile.fetchProfiles.useQuery({
    search: profleSearchData?.search,
    guests: Number(profleSearchData?.guests ?? 1),
    ageRange:
      profleSearchData?.ageRange?.split("-")?.map((i) => Number(i)) ??
      undefined,
    city: profleSearchData?.city,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <ProfileSearchForm
          onSubmit={(data) => {
            console.log(data);
            setProfleSearchData(data);
          }}
        />
        {profiles && <ProfileList profiles={profiles} />}
        <ProfileSetupForm />
      </main>
    </>
  );
}
