import Head from "next/head";
import { Hero } from "~/components/landing/Hero";
import { MeetTheMacedoniansIntro } from "~/components/landing/MeetTheMacedoniansIntro";
import { ProfileSearchForm } from "~/components/profile/ProfileSearchForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Meet The Macedonians</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <Hero />
        <ProfileSearchForm
          onSubmit={(data) => {
            console.log(data);
          }}
        />
        <MeetTheMacedoniansIntro />
      </main>
    </>
  );
}
